/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unirc.LiangScheme.policyManagement;

public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(PolicyParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b9bae60cdc3faa29aaefa1f9bffa345 (do not edit this line) */
