/* Generated By:JavaCC: Do not edit this line. PolicyParserTreeConstants.java Version 5.0 */
package it.unirc.LiangScheme.policyManagement;

public interface PolicyParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSION = 2;
  public int JJTOF = 3;
  public int JJTATTRIBUTE = 4;
  public int JJTNUMERICALATTRIBUTE = 5;
  public int JJTGEOHASHATTRIBUTE = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Expression",
    "Of",
    "Attribute",
    "NumericalAttribute",
    "GeoHashAttribute",
  };
}
/* JavaCC - OriginalChecksum=a9c1f53f5cf3523101d09c854717ba52 (do not edit this line) */
